controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    strip.setAll(0xff0000)
    strip.show()
})
let strip: light.NeoPixelStrip = null
let mySprite = sprites.create(img`
    .............ccfff..............
    ...........ccddbcf..............
    ..........ccddbbf...............
    ..........fccbbcf...............
    .....fffffccccccff.........ccc..
    ...ffbbbbbbbcbbbbcfff....ccbbc..
    ..fbbbbbbbbcbcbbbbcccff.cdbbc...
    ffbbbbbbffbbcbcbbbcccccfcdbbf...
    fbcbbb11ff1bcbbbbbcccccffbbf....
    fbbb11111111bbbbbcccccccbbcf....
    .fb11133cc11bbbbcccccccccccf....
    ..fccc31c111bbbcccccbdbffbbcf...
    ...fc13c111cbbbfcddddcc..fbbf...
    ....fccc111fbdbbccdcc.....fbbf..
    ........ccccfcdbbcc........fff..
    .............fffff..............
    `, SpriteKind.Player)
mySprite.setStayInScreen(true)
strip = light.createStrip(pins.LED, 25)
strip.setBrightness(32)
strip.clear()
strip.show()
game.onUpdate(function () {
    controller.moveSprite(mySprite)
})
